import RPi.GPIO as IO          
import time
IO.setmode (IO.BOARD)
IO.setup(11,IO.OUT)
IO.output(11,1)
time.sleep(1)
IO.cleanup()
time.sleep(1)                        
IO.setmode (IO.BOARD)
IO.setup(11,IO.OUT)
IO.output(11,1)
time.sleep(1)
IO.cleanup()
time.sleep(1)
IO.setmode (IO.BOARD)
IO.setup(11,IO.OUT)
IO.output(11,1)
time.sleep(1)
IO.cleanup()
time.sleep(1)